# Generated by Django 3.1.1 on 2020-09-25 05:40

from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List = []

    operations = [
        migrations.CreateModel(
            name="Hedgehog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("color", models.CharField(default="blue", max_length=32)),
                ("age", models.IntegerField(default=0)),
            ],
        ),
    ]
