# Generated by Django 3.2.9 on 2022-03-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='hedgehog',
            name='array',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='array', to='test_app.arraymodel'),
        ),
    ]
