name: CI

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: python setup.py develop && pip install -r requirements-test.txt
      - name: Lint
        run: python runtests.py --lint-only

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django-version: ["Django==3.2.9", "Django==3.1.13"]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python setup.py develop && pip install -r requirements-test.txt
      - name: Install specific Django version ${{ matrix.django-version }}
        run: pip install ${{ matrix.django-version }}
      - name: Tests
        run: python runtests.py --no-lint
